name: "air_traffic_analytics"
version: "1.0.0"
config-version: 2

profile: "air_traffic_analytics"

vars:
  lake_root: "../../../lake"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  air_traffic_analytics:
    +materialized: view
